site_name:        DIVAnd.jl
repo_url:         https://github.com/gher-ulg/DIVAnd.jl
site_description: an n-dimensional variational analysis of arbitrarily located observations
site_author:      Alexander Barth, Jean-Marie Beckers

theme: mkdocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md